# Generated by Django 5.1.15 on 2026-10-01 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g. 'Games', 'Executables', 'Tools')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of this category')),
                ('icon', models.CharField(blank=True, help_text='Optional icon glyph, badge symbol, or emoji', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order on project tabs')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('tagline', models.CharField(help_text='One-line summary for listing cards.', max_length=300)),
                ('description', models.TextField(help_text='Project details, controls, instructions (Markdown supported).')),
                ('download_file', models.FileField(blank=True, help_text='Upload packaged executable or archive (.exe, .zip, etc.)', null=True, upload_to='downloads/')),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('platform', models.CharField(default='Windows x64', help_text='Target platform (e.g., Windows x64, Cross-platform, Portable)', max_length=100)),
                ('system_requirements', models.CharField(blank=True, help_text='e.g., Windows 10/11, Dedicated GPU recommended', max_length=255)),
                ('github_url', models.URLField(blank=True, help_text='Optional GitHub repository link')),
                ('itch_url', models.URLField(blank=True, help_text='Optional Itch.io page link')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, help_text='Optional SEO description override.', max_length=160)),
                ('project_type', models.ForeignKey(blank=True, help_text='Choose or create categories under Project Categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'verbose_name': 'Project / Downloadable Work',
                'verbose_name_plural': 'Projects & Downloads',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
    ]
