# Generated by Django 5.1.15 on 2026-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projectcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Project screenshot, cover art, or interface preview.', null=True, upload_to='projects/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='show_download_button',
            field=models.BooleanField(default=True, help_text='Toggle displaying the download button at the top of the project page and cards.'),
        ),
        migrations.AddField(
            model_name='project',
            name='show_featured_image',
            field=models.BooleanField(default=True, help_text='Toggle displaying the featured image on the project page.'),
        ),
    ]
