# Generated by Django 5.1.15 on 2026-10-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_image_project_show_download_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_url',
            field=models.URLField(blank=True, help_text='Optional direct or external download URL (e.g. Google Drive, itch.io, GitHub release, CDN). Used if no file is uploaded directly.', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='download_file',
            field=models.FileField(blank=True, help_text='Upload packaged executable or archive (.exe, .zip, etc.) directly.', null=True, upload_to='downloads/'),
        ),
    ]
