# Generated by Django 5.1.15 on 2026-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About HudIsThinking LLC', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Markdown supported. Leave blank or edit anytime via Django admin.')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines.', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL slug (e.g. 'manifesto' makes it accessible at /manifesto/)", max_length=200, unique=True)),
                ('content', models.TextField(help_text='Page body content (Markdown and HTML supported).')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Standalone Page',
                'verbose_name_plural': 'Custom Standalone Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DBTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template path to override (e.g. 'base.html', 'home.html', 'about.html', 'philosophy/list.html', 'philosophy/detail.html', 'projects/list.html', 'projects/detail.html')", max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text='Brief note describing what this template is used for.', max_length=255)),
                ('content', models.TextField(help_text='HTML / Django template source code. Edit directly in your browser.')),
                ('is_active', models.BooleanField(default=True, help_text='When checked, this database template overrides the filesystem template. Uncheck to revert to default.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Editable Template (DB)',
                'verbose_name_plural': 'Editable Templates (DB)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display label (e.g., 'Philosophy', 'Projects')", max_length=80)),
                ('url', models.CharField(help_text="URL path (e.g. '/philosophy/', '/projects/', '/about/', or full 'https://...')", max_length=255)),
                ('location', models.CharField(choices=[('header', 'Header Navigation'), ('footer', 'Footer Links')], default='header', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in navigation bar (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Navigation Menu Link',
                'verbose_name_plural': 'Navigation Menu Links',
                'ordering': ['location', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='HudIsThinking', max_length=150)),
                ('llc_name', models.CharField(default='HudIsThinking LLC', max_length=150)),
                ('tagline', models.CharField(default='Personal archive of philosophical arguments and software works.', max_length=300)),
                ('logo', models.ImageField(blank=True, help_text='Custom site logo (defaults to the H.I.T. book icon if empty).', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Custom browser tab icon (.ico or .png).', null=True, upload_to='branding/')),
                ('meta_description', models.TextField(blank=True, default='Personal archive of philosophical arguments and software works.', help_text='Global SEO meta description.')),
                ('enable_wisps', models.BooleanField(default=True, help_text='Toggle the floating background firefly wisps.')),
                ('wisp_count', models.PositiveIntegerField(default=16, help_text='Number of floating wisps in background (recommended: 10-25).')),
                ('wisp_speed', models.FloatField(default=0.08, help_text='Drift speed multiplier (recommended: 0.04 to 0.15).')),
                ('custom_css', models.TextField(blank=True, help_text='Raw CSS injected into all pages. Use this to tweak colors, fonts, or borders directly from admin.')),
                ('custom_head_code', models.TextField(blank=True, help_text='Custom HTML/scripts to inject into <head> (e.g., custom analytics or font tags).')),
            ],
            options={
                'verbose_name': 'Site Configuration & Branding',
                'verbose_name_plural': 'Site Configuration & Branding',
            },
        ),
    ]
