# Generated by Django 5.1.15 on 2026-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About HudIsThinking LLC', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Markdown supported. Leave blank or edit anytime via Django admin.')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines.', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
