# Generated by Django 5.1.15 on 2026-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title or label for this media asset.', max_length=200)),
                ('file', models.FileField(help_text='Upload any image, document, archive, or binary.', upload_to='library/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document / PDF'), ('binary', 'Executable / Archive'), ('audio', 'Audio'), ('other', 'Other')], default='image', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Brief notes or caption.', max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Library',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Header or profile image for the About page.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='show_featured_image',
            field=models.BooleanField(default=True, help_text='Toggle displaying the featured image on the About page.'),
        ),
        migrations.AddField(
            model_name='custompage',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Optional header image for this page.', null=True, upload_to='pages/images/'),
        ),
        migrations.AddField(
            model_name='custompage',
            name='show_featured_image',
            field=models.BooleanField(default=True, help_text='Toggle displaying the featured image on this page.'),
        ),
    ]
