# Generated by Django 5.1.15 on 2026-10-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediaitem_aboutpage_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='[COMMUNITY & DIALECTIC PLATFORM]', max_length=100)),
                ('title', models.CharField(default='HudIsThinking Connect', max_length=200)),
                ('subtitle', models.CharField(default='Independent philosophical publishing, live debate scheduling, and peer inquiry.', max_length=400)),
                ('cta_label', models.CharField(default='LAUNCH CONNECT ->', max_length=100)),
                ('cta_url', models.CharField(default='https://connect.hudisthinking.com/', max_length=255)),
                ('destination_label', models.CharField(default='connect.hudisthinking.com', max_length=100)),
                ('pillar_1_title', models.CharField(default='Publish & Host Philosophy', max_length=200)),
                ('pillar_1_desc', models.TextField(default='A dedicated home for independent authors and thinkers to publish formal philosophical works. Retain full authorship over arguments, systematic treatises, logic proofs, and essays within an archive designed for long-form contemplation rather than ephemeral feeds.')),
                ('pillar_2_title', models.CharField(default='Schedule Live Debates', max_length=200)),
                ('pillar_2_desc', models.TextField(default='Organize and schedule live, real-time verbal or written debates with other philosophers. Set clear formal theses, establish dialectical constraints, agree on rules of engagement, and hold structured intellectual discourse in front of peers.')),
                ('pillar_3_title', models.CharField(default='Premise & Argument Discussions', max_length=200)),
                ('pillar_3_desc', models.TextField(default='Engage deeply with works published by others. Start focused discussion threads dissecting individual premises, formulate rigorous counter-arguments, present counter-examples, and develop collaborative dialectical rebuttals.')),
                ('pillar_4_title', models.CharField(default='Dialectical Network', max_length=200)),
                ('pillar_4_desc', models.TextField(default='Connect directly with peers pursuing epistemology, metaphysics, ethics, theology, and philosophical logic. Build an ongoing intellectual record and participate in a community founded on analytical rigor and open inquiry.')),
                ('callout_heading', models.CharField(default='ENTER THE PLATFORM', max_length=200)),
                ('callout_body', models.TextField(default='Connect is an external standalone portal within the HudIsThinking ecosystem. Create an account, browse published philosophical treatises, schedule upcoming debates, or publish your own work today.')),
                ('callout_cta_label', models.CharField(default='VISIT CONNECT.HUDISTHINKING.COM ->', max_length=100)),
                ('callout_cta_url', models.CharField(default='https://connect.hudisthinking.com/', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Connect Page',
                'verbose_name_plural': 'About Connect Page',
            },
        ),
    ]
