# Generated by Django 5.1.15 on 2026-10-01 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhilosophyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g. 'Arguments', 'Essays', 'Metaphysics')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of this category')),
                ('icon', models.CharField(blank=True, help_text='Optional icon glyph, badge symbol, or emoji', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order on archive tabs')),
            ],
            options={
                'verbose_name': 'Philosophy Category',
                'verbose_name_plural': 'Philosophy Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('thesis', models.CharField(blank=True, help_text='Brief thesis statement or core premise summary', max_length=350)),
                ('content', models.TextField(help_text='Full text (Markdown supported).')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, help_text='Optional SEO description override. If left blank, uses thesis or title.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO metadata.', max_length=255)),
                ('category', models.ForeignKey(blank=True, help_text='Choose or create categories under Philosophy Categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arguments', to='philosophy.philosophycategory')),
            ],
            options={
                'verbose_name': 'Philosophical Argument / Writing',
                'verbose_name_plural': 'Philosophy Archive',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
