# Generated by Django 5.1.15 on 2026-10-01 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('argument', 'Philosophical Argument'), ('essay', 'Essay'), ('blog', 'Blog Post'), ('fragment', 'Fragment / Note')], default='argument', max_length=50)),
                ('thesis', models.CharField(blank=True, help_text='Brief thesis statement or core premise summary', max_length=350)),
                ('content', models.TextField(help_text='Full text (Markdown supported).')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, help_text='Optional SEO description override. If left blank, uses thesis or first sentences.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO metadata.', max_length=255)),
            ],
            options={
                'verbose_name': 'Philosophical Argument / Writing',
                'verbose_name_plural': 'Philosophy Archive',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
