# Generated by Django 5.1.15 on 2026-10-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philosophy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='philosophycategory',
            name='icon',
        ),
    ]
