# Generated by Django 5.1.15 on 2026-10-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philosophy', '0002_remove_philosophycategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilosophyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name (e.g. Ethics, Meta-Ethics, Metaphysics, Free Will)', max_length=80, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=80, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the philosophical domain')),
            ],
            options={
                'verbose_name': 'Philosophy Tag',
                'verbose_name_plural': 'Philosophy Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='argument',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select or create tags such as Ethics, Meta-Ethics, Metaphysics, Free Will', related_name='arguments', to='philosophy.philosophytag'),
        ),
    ]
