# Generated by Django 5.1.15 on 2026-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philosophy', '0003_philosophytag_argument_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='citation_apa',
            field=models.TextField(blank=True, help_text='Custom APA citation override. Leave blank to auto-generate.'),
        ),
        migrations.AddField(
            model_name='argument',
            name='citation_mla',
            field=models.TextField(blank=True, help_text='Custom MLA citation override. Leave blank to auto-generate.'),
        ),
        migrations.AddField(
            model_name='argument',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Header artwork or illustrative diagram for this argument.', null=True, upload_to='philosophy/images/'),
        ),
        migrations.AddField(
            model_name='argument',
            name='justifications',
            field=models.TextField(blank=True, help_text='Justifications and elaborations breaking down what warrants each premise (Markdown supported).'),
        ),
        migrations.AddField(
            model_name='argument',
            name='references',
            field=models.TextField(blank=True, help_text='Sources, literature citations, and bibliography (Markdown supported).'),
        ),
        migrations.AddField(
            model_name='argument',
            name='show_featured_image',
            field=models.BooleanField(default=True, help_text='Toggle displaying the featured image on this argument page.'),
        ),
    ]
